# Generated by Django 4.2.7 on 2023-11-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, verbose_name="ключ")),
            ],
            options={
                "verbose_name": "Ключ",
                "verbose_name_plural": "Ключи",
            },
        ),
        migrations.CreateModel(
            name="Translate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translate", models.TextField(max_length=2048, verbose_name="Текст")),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_text",
                        to="backend.language",
                    ),
                ),
                (
                    "text_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_translates",
                        to="backend.text",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текст на языке",
                "verbose_name_plural": "Тексты на языках",
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=20, verbose_name="Телеграм ID"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="Пользователь"),
                ),
                (
                    "selected_language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_with_lang",
                        to="backend.language",
                        verbose_name="язык Бота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
