# Generated by Django 4.2.7 on 2023-12-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_telegramuser_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="selected_group",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=512,
                null=True,
                verbose_name="Группа пользователя",
            ),
        ),
    ]
